# As per the GitHub recommendations, we should update
# the major and minor tags (ie v1, v1.1) to point to the
# latest release.
# See: https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management
name: Update major and minor tags post release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  update-major-and-minor-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-update-semver@v1